services:
  - name: tcp-echo-server
    type: web
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: / # Render requires a health check path even for TCP
    envVars:
      - key: PORT
        value: '9000'
