services:
  - type: web
    name: smoke-test
    env: docker
    envVars:
      - key: PORT
        value: '9000'
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    autoDeploy: true
